# ===========================================
# 운영 환경 설정 (환경변수로 주입)
# ===========================================

spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false

jwt:
  secret: ${JWT_SECRET}
  access-token-validity: ${JWT_ACCESS_TOKEN_VALIDITY}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}
  access-header: ${JWT_ACCESS_HEADER}
  grant-type: ${JWT_GRANT_TYPE}


app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}
  oauth2:
    redirect-uri: ${OAUTH2_REDIRECT_URI}

client:
  kakao:
    name: ${KAKAO_NAME}
    client-id: ${KAKAO_CLIENT_ID}
    public-key-url: ${KAKAO_PUBLIC_KEY_URL}

spring.data.redis:
  host: ${REDIS_HOST}
  port: ${REDIS_PORT}
  password: ${REDIS_PASSWORD}